{
    imports = [
        ./obs-studio.nix
        ./cheese.nix
        ./audacity.nix
        ./blockbench.nix
        ./blender.nix
        ./gimp.nix
        ./kdeConnect.nix
        ./gparted.nix
        ./kate.nix
        ./syncthing.nix
        ./realvnc.nix
        ./wireguard-gui.nix
        ./godot.nix
        ./kruler.nix
        ./cpu-x.nix
        ./libreoffice.nix
        ./anydesk.nix
        ./scrcpy.nix
        ./kdenlive.nix
        ./rustdesk.nix
    ];
}