{
    imports = [
        ./filebrowser.nix
        ./it-tools.nix
        ./jellyfin.nix
        ./ntfy.nix
        ./speedtest-tracker.nix
        ./glance.nix
        ./vaultwarden.nix
        ./zipline.nix
        ./umami.nix
        ./postgresql.nix
        ./linkwarden.nix
        ./convertx.nix
        ./meilisearch.nix
        ./syncthing.nix
        ./searxng.nix
        ./grafana.nix
        ./lyrics-api.nix
        ./likeify.nix
        ./discord-user-apps.nix
        ./apprise-api.nix
        ./pi-hole.nix
        ./create-addons.nix
        ./personal-site.nix
        ./receiptify.nix
        ./wireguard.nix
        ./api.nix
        ./nginx.nix
        ./mailcow-dockerized.nix
        ./mongodb.nix
        # ./weblate.nix
        ./fail2ban.nix
        ./cloud-init.nix
        ./prometheus
        ./your_spotify
        ./create-addons-notifier
    ];
}