{
    imports = [
        ./filebrowser.nix
        ./it-tools.nix
        ./jellyfin.nix
        ./ntfy.nix
        ./your_spotify
        ./speedtest-tracker.nix
        ./glance.nix
        ./vaultwarden.nix
        ./zipline.nix
        ./umami.nix
        ./postgresql.nix
        ./linkwarden.nix
        ./convertx.nix
        ./meilisearch.nix
        ./syncthing.nix
        ./searxng.nix
        ./grafana.nix
        ./lyrics-api.nix
        ./likeify.nix
        ./discord-user-apps.nix
        ./apprise-api.nix
        ./pi-hole.nix
        ./prometheus
    ];
}