keys:
  - &master age15c35gtvl0lutpa72k5fvazfaa4te344kunv7scld5zfdukmr8fcsh3rvdp
  - &nixos_admin age1s3396w9rdxrsl4czndquxnkm27kj5p4996ndlmmvdpmp3dxdp3rq9w5z8h
  - &nixos_server age1st4ru7dkrv2faxm2s2snf7pzpzddysvfvlsvtpsdfth78gwhvazs6vrsfv
  - &server_server age15lnh66ahplgejexktgvy242e9pntuqjka45tz43zds7wkl5q8fwqlgs9ma

creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
      - age:
          - *master
          - *nixos_admin
          - *nixos_server
          - *server_server